<?php echo $this->getButtonHtml() ?>

<span class="collect-indicator" id="request_state_span" style="margin-left:10px;">
    <span id="fastly_request_state_message_span"><b>Current state:</b>
        <img class="processing" id="io-processing" alt="Collecting" style="display:none; margin:0 5px" src="<?php echo Mage::getDesign()->getSkinBaseUrl(array('_area'=>'adminhtml')).'images/rule-ajax-loader.gif'?>"/>
        <span style="display:none;" class="request_io_state_span" id="io_state_enabled"> enabled</span>
        <span style="display:none;" class="request_io_state_span" id="io_state_disabled"> disabled</span>
        <span style="display:none;" class="request_io_state_span" id="io_state_unknown"> unknown</span>
    </span>
</span>

<ul class="messages button-messages" id="toggle-io-btn-success" style="display: none;">
    <li class="success-msg">
        <ul>
            <li>
                <span></span>
            </li>
        </ul>
    </li>
</ul>

<ul class="messages button-messages" id="toggle-io-btn-error" style="display: none;">
    <li class="error-msg">
        <ul>
            <li>
                <span></span>
            </li>
        </ul>
    </li>
</ul>

<ul class="messages button-messages" id="toggle-io-btn-warning" style="display: none;">
    <li class="warning-msg">
        <ul>
            <li>
                <span>Please contact your sales rep or send an email to support@fastly.com to request image optimization activation for your Fastly service.</span>
            </li>
        </ul>
    </li>
</ul>

<style type="text/css">
    #io_state_enabled {
        color: #008000;
    }

    #io_state_disabled {
        color: #808080;
    }

    #io_state_unknown {
        color: #ff0000;
    }
</style>