<?php echo $this->getButtonHtml() ?>

<ul class="messages button-messages" id="vcl-upload-btn-success" style="display: none;">
    <li class="success-msg">
        <ul>
            <li>
                <span></span>
            </li>
        </ul>
    </li>
</ul>

<ul class="messages button-messages" id="vcl-upload-btn-error" style="display: none;">
    <li class="error-msg">
        <ul>
            <li>
                <span></span>
            </li>
        </ul>
    </li>
</ul>